[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[inet_http_server]
port=127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://127.0.0.1:9001

[program:init]
command=python3 /app/init.py
stdout_logfile=/var/log/init.log
stderr_logfile=/var/log/init.log
autorestart=false
startsecs=0

[program:replicator]
command=python3 /app/replicator.py
stdout_logfile=/var/log/replicator.log
stderr_logfile=/var/log/replicator.log
autostart=false
autorestart=true
